GET {{url}}/api/operationPartner/?page=0&pageItems=1000&searchWord=&sort=name%20ASC&idOperation=81
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6WyJhZG1pYXNAaWFzZGlnaXRhbGdyb3VwLmNvbSIsImFkbWlhc0BpYXNkaWdpdGFsZ3JvdXAuY29tIl0sImp0aSI6IjlkYmI2ZmE3N2ViZjRiMjE5YmY1NWM3YzcwN2E4YWNlIiwicm9sZSI6ImFkbWluaXN0cmF0b3IiLCJvcGVyYXRpb25QYXJ0bmVySWQiOiIwIiwib3BlcmF0aW9uSWQiOiI4MSIsInBhcnRuZXJJZCI6IjAiLCJpZCI6IjEwOSIsIm5hbWUiOiJhZG0iLCJzdXJuYW1lIjoiaWFzIiwicGljdHVyZSI6IiIsImluaXRpYWxzIjoiYWkiLCJtb2R1bGVzIjoicHJvbW90ZXJ8b3BlbiIsInJvbGVOYW1lIjoiQWRtaW5pc3RyYWRvciIsIm5iZiI6MTU5NjExMTU3NiwiZXhwIjoxNTk2Mjg0Mzc2LCJpYXQiOjE1OTYxMTE1NzYsImlzcyI6IlJlYmVucyIsImF1ZCI6IlJlYmVucyJ9.bhs_pRC_aiv0iSIYs3oI_vatmxzsiLN2cEialonBSbgazNGLWWHDEOdv1wA3y-eLVpTn31Gh_z6vSsXIJeaeHU0UpEtuKR-Lyg8pX9sA8njFimUpmHuxmMklJKzLArxOjZi1j2rlSlVAkSXwqXYqfABOaNTyiqW40jsSzTYBM5RaAihNjPiSv4YzZWbtnbXZ_W3K4x3S7H-4LqVMNUneGx4guybtAF1iRcNM_F2M3sXYBbjvJiDmhLmPJj7tydYEuX2M9IxmI4SuT290zglvIOTPt1Li8SPM3zP6DUF1zzRP6DiigNuqrR17VZsOMdCfMbMd-iiLvI4TVVszEFLvzg
