GET {{url}}/api/Wirecard
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6WyJpc3JhZWxAaWFzZGlnaXRhbGdyb3VwLmNvbSIsImlzcmFlbEBpYXNkaWdpdGFsZ3JvdXAuY29tIl0sImp0aSI6ImFiMmU1MjBmMjhkOTQyNDFiZjUyYzBlMmZkNWRiMmY4Iiwicm9sZSI6Im1hc3RlciIsIm9wZXJhdGlvblBhcnRuZXJJZCI6IjAiLCJvcGVyYXRpb25JZCI6IjAiLCJpZCI6IjEiLCJuYW1lIjoiTWFzdGVyIC0gQWRtIC0gSXNyYWVsIFNpbHZhIiwic3VybmFtZSI6IiIsInBpY3R1cmUiOiIiLCJpbml0aWFscyI6Ik0iLCJtb2R1bGVzIjoiIiwicm9sZU5hbWUiOiJNYXN0ZXIiLCJuYmYiOjE1OTU1MzkyMjQsImV4cCI6MTU5NTcxMjAyNCwiaWF0IjoxNTk1NTM5MjI0LCJpc3MiOiJSZWJlbnMiLCJhdWQiOiJSZWJlbnMifQ.a6IW1YQm9kCVm8hI3kDeeQjObHDKX9HfIzBijFXNNLooRHrEqsMYORktgcY8g4w7nBYmzcZ_TlBV3zk0UUIaYMImkHrjH-earc2O34B5UH1QSpfUNgUV3BZuRnUe14gpw_bkPbRo57R_3OvjYbvjBbsfji2YsVK8IWN_gQOR2L6Y2TR1fUH71EBNiV-i26yA9T2w1L6LFPux6Qgd95nKDdJIckByGQvZBdLaY0l5KXytq7aTOw-dAbB61obhoO4WOC-RvRig61lIdL6x5qkjJDkeJvowTVPcKSVd9X-r_kXdmM1Y7WiKTNvzqgu_wbYpaDXkMeOP-8qSclJ8RDLbZA

###

GET {{url}}/api/Wirecard/GenerateExcel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6WyJpc3JhZWxAaWFzZGlnaXRhbGdyb3VwLmNvbSIsImlzcmFlbEBpYXNkaWdpdGFsZ3JvdXAuY29tIl0sImp0aSI6IjFiMmE0NTQ1YTVkYjQ2MGNhMzQ2MjkxMTNjYmZkOTZjIiwicm9sZSI6Im1hc3RlciIsIm9wZXJhdGlvblBhcnRuZXJJZCI6IjAiLCJvcGVyYXRpb25JZCI6IjAiLCJpZCI6IjEiLCJuYW1lIjoiTWFzdGVyIC0gQWRtIC0gSXNyYWVsIFNpbHZhIiwic3VybmFtZSI6IiIsInBpY3R1cmUiOiIiLCJpbml0aWFscyI6Ik0iLCJtb2R1bGVzIjoiIiwicm9sZU5hbWUiOiJNYXN0ZXIiLCJuYmYiOjE1OTU1NDAxMjgsImV4cCI6MTU5NTcxMjkyOCwiaWF0IjoxNTk1NTQwMTI4LCJpc3MiOiJSZWJlbnMiLCJhdWQiOiJSZWJlbnMifQ.UTwnsYd6sgZiZ8t5sr12ZOGYrXc57_ckQN12dnWGT9CDxgs-uoltGPnfQS0XEo0ibjKRdOw9qEOfYuRq4wpOGENdip88RmyEwvau1BjV1q17r6m5A6iIsehFZa_FOL5VbYAVncm9nkY7KNpj9vmZWaJVSk7m4iNpnuZTQqHXTio_I73rg88AlZxYRfpt4WwP_qdgJCoDaA_TZtZBWRK0bKhLCahwGH6hrWZjQnfe8IRgCPnHpiyDeT9gGNxPJlTzMFAZs3o-XoPiwKD1RsgK-2fxamdx0XeAnlpyKXyCf4iPBEaP9rMcb2KiXGavfvZ0FZLsO6z5c7o8k_A9PIvbmA